# Shell
shell /usr/bin/fish --login --interactive

# --- Splits (kitty calls them "windows") ---

# Create new splits
map alt+shift+j launch --location=hsplit
map alt+shift+k launch --location=hsplit
map alt+shift+l launch --location=vsplit
map alt+shift+h launch --location=vsplit

# Navigate between splits
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right
map alt+h neighboring_window left

scrollback_pager nvim +Man!

# Font (Ghostty default)
font_family      JetBrains Mono
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
font_size        12.0

# Colors (Ghostty Default StyleDark)
background            #292c33
foreground            #ffffff
cursor                #ffffff

selection_background  #ffffff
selection_foreground  #ffffff

# 16-color palette
color0   #1d1f21
color1   #bf6b69
color2   #b7bd73
color3   #e9c880
color4   #88a1bb
color5   #ad95b8
color6   #95bdb7
color7   #c5c8c6
color8   #666666
color9   #c55757
color10  #bcc95f
color11  #e1c65e
color12  #83a5d6
color13  #bc99d4
color14  #83beb1
color15  #eaeaea
