# Shell
shell /usr/bin/fish --login --interactive

# --- Splits (kitty calls them "windows") ---

# Create new splits
map alt+shift+j launch --location=hsplit
map alt+shift+k launch --location=hsplit
map alt+shift+l launch --location=vsplit
map alt+shift+h launch --location=vsplit

# Navigate between splits
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right
map alt+h neighboring_window left

scrollback_pager nvim -c "set nonumber nolist showtabline=0 foldcolumn=0" -c "autocmd TermOpen * normal G" -c "silent write /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "
