[ -f ~/.config/zsh/config.zsh] && source ~/.config/zsh/config.zsh
[ -f ~/.zsh/antigen.zsh ] && source ~/.zsh/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions

antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

alias vim='nvim'

alias gst='git status'
alias gdiff='git diff'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
